### ISSUE TITLE
Can't download version 1 of the github action

### ISSUE THREAD

**Issue by shehackspurple** [federacy/scan-action#1]
Hi,

Every time I run your action I get the following message:
Download action repository 'federacy/scan-action@v1'
##[warning]Failed to download action 'https://api.github.com/repos/federacy/scan-action/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 21.185 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/federacy/scan-action/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 29.538 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).

You can see me running it here:
https://github.com/shehackspurple/dotnetcore-webapp/runs/426644334?check_suite_focus=true 

Any help would be great, thanks!

**Comment by jsulinski** [comment]
I think this is because the current release is 0.1.1 rather than v1. Will dig in and keep you posted.

**Comment by jsulinski** [comment]
Confirmed and resolved in https://github.com/federacy/scan-action/pull/2. Let me know if that works for you?

**Comment by jsulinski** [comment]
by the way, I don't think [Salus](https://github.com/coinbase/salus) has a .net scanner integration, so the only one that would benefit `dotnetcore-webapp` might be [PatternSearch](https://github.com/coinbase/salus/blob/master/docs/scanners/pattern_search.md).

~~This Github Action doesn't support passing in the configuration required for the PatternSearch scanner yet~~ (this can be accomplished by using a custom configuration and configuration cascading functionality in Salus). The [CircleCI Orb](https://github.com/federacy/salus-orb) does by utilizing a custom configuration file (in your repo). The SecureDevelopment website also doesn't support this scanner currently, but you'll see the results in Github. 

Thanks a lot for letting me know about the outdated documentation!

**Comment by shehackspurple** [comment]
If it doesn't support .Net then that's the problem. Could you update the documentation to make that more clear? I will close this issue. Thanks for your help.

**Comment by jsulinski** [comment]
@shehackspurple I've updated the documentation to bring the scanners supported front and center. Previously they were only listed under inputs and in the Salus documentation. PR is here: https://github.com/federacy/scan-action/pull/3

Also went ahead and forked your dotnetcore-webapp repo and added the PatternSearch scanner, which uses a go library called 'sift'. This scanner is probably not super useful, I've added a rule looking for private keys. It would be great if Salus had more integrations. 

Commit is here: https://github.com/jsresearch/dotnetcore-webapp/commit/7a9acc931b8513a4aebdb3e6764d1cebdb0a70ed

The output of the action is here: https://github.com/jsresearch/dotnetcore-webapp/runs/464088167?check_suite_focus=true

Gitlab has some similar projects to Salus, but they're all EE licensed: https://gitlab.com/gitlab-org/security-products/analyzers

The .net scanner they seem to be using is: https://security-code-scan.github.io/
